# Use a lightweight JDK base image
FROM adoptopenjdk:17-jdk-hotspot AS build

# Set the working directory in the container
WORKDIR /app

# Copy the packaged JAR file into the container
COPY target/*.jar /app/app.jar

# Expose the port that the application will listen on
EXPOSE 7070

# Command to run the application when the container starts
CMD ["java", "-jar", "app.jar"]
